title: isixline
author: isixline
email: isixline@qq.com
show_excerpts: true

sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: isixline
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"
  style: black
  showNav: false
  showPicker: false

  social_links:
    twitter: isixline
    github:  isixline
    linkedIn: in/航-刘-065130170
    rss: rss
 

plugins:
  - jekyll-seo-tag